name: test_devcontainer_image_build

on:
  - push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  test_devcontainer_image_build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Build devcontainer image
        uses: devcontainers/ci@v0.3
        with:
          push: never
